uploads = []

[[generated]]
id = "jTN66yt-5ujQLr2JnrWxC"
uri = "file://artifacts/velmora/public/images/perfume-1.png"
type = "image"
title = "Luxury perfume bottle gold dark"

[[generated]]
id = "UlV1v-S_eVZ8rtQEE9LAp"
uri = "file://artifacts/velmora/public/images/perfume-2.png"
type = "image"
title = "Elegant feminine perfume dark"

[[generated]]
id = "n2vMlLHyW2nLJYEInfOkv"
uri = "file://artifacts/velmora/public/images/perfume-3.png"
type = "image"
title = "Masculine luxury cologne dark"

[[generated]]
id = "EdiZ7TlwY9X3nQk3aeAcf"
uri = "file://artifacts/velmora/public/images/hero.png"
type = "image"
title = "Luxury perfume hero banner"

[[outputs]]
id = "u2KLo8t4P3vILwR_WogIm"
uri = "file://exports/utilisateurs.csv"
type = "table"
title = "utilisateurs.csv — المستخدمون"

[[outputs]]
id = "svNvx-R1LR04AeffFCNhI"
uri = "file://exports/produits.csv"
type = "table"
title = "produits.csv — المنتجات (25 منتج)"

[[outputs]]
id = "uzMgK4rgO9Yo8BK6os2dk"
uri = "file://exports/commandes.csv"
type = "table"
title = "commandes.csv — الطلبيات"

[[outputs]]
id = "9eSlxxo120z1nta6QI8CQ"
uri = "file://exports/commande_items.csv"
type = "table"
title = "commande_items.csv — تفاصيل الطلبيات"

[[outputs]]
id = "ch3T8xHVtJmuQ5tsc6YAb"
uri = "file://exports/panier_items.csv"
type = "table"
title = "panier_items.csv — سلة التسوق"
