[[pages]]
path = "/"
screenshotTimestamp = "2026-05-03T10:57:19Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afe51ad-0c79-4dd0-a17f-f296a592e094/0cbf63df-c796-4e90-a9f4-73cf9b813017/7XYU7yf"

[[pages]]
path = "/produits/1"
screenshotTimestamp = "2026-05-03T00:37:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afe51ad-0c79-4dd0-a17f-f296a592e094/0cbf63df-c796-4e90-a9f4-73cf9b813017/DlyDohC"

[[pages]]
path = "/produits"
screenshotTimestamp = "2026-05-03T00:43:53Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afe51ad-0c79-4dd0-a17f-f296a592e094/0cbf63df-c796-4e90-a9f4-73cf9b813017/9VERNLE"

[[pages]]
path = "/admin"
screenshotTimestamp = "2026-05-03T10:53:34Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afe51ad-0c79-4dd0-a17f-f296a592e094/0cbf63df-c796-4e90-a9f4-73cf9b813017/DwUjGnD"
